version: 0.2

phases:
  install:
    runtime-versions:
      # Utilizando o Python 3.12 conforme definido na sua infraestrutura e Dockerfile [cite: 31, 46]
      python: 3.12 
    commands:
      - echo "Instalando dependências do Python e ferramentas de teste/segurança..."
      - pip install -r src/api/requirements.txt
      - pip install pylint bandit pytest checkov
      - echo "Instalando o TFLint..."
      - curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

  pre_build:
    commands:
      - echo "Fase de Testes Iniciada"
      
      - echo "1. Executando PyLint (Qualidade do código Python)..."
      - pylint src/api/app.py
      
      - echo "2. Executando Bandit (Segurança do código Python)..."
      - bandit -r src/api/
      
      - echo "3. Executando Testes Unitários com Pytest..."
      - pytest src/api/test_app.py || echo "Aviso: test_app.py ainda será criado na próxima etapa!"
      
      - echo "4. Executando TFLint (Qualidade do Terraform)..."
      - tflint --init
      - tflint
      
      - echo "5. Executando Checkov (Segurança da Infraestrutura)..."
      - checkov -d . --framework terraform
      
      - echo "6. Autenticando no Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo "Build iniciado na data `date`"
      - echo "Construindo a imagem Docker..."
      # Usaremos o hash do commit do Git como tag da imagem para rastreabilidade
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG src/api/
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo "Build completado na data `date`"
      - echo "Enviando a imagem Docker para o repositório ECR..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo "Criando o arquivo imagedefinitions.json..."
      # O ECS Fargate precisa deste arquivo para saber qual container atualizar no Deploy
      - printf '[{"name":"app","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json